server:
  servlet:
    context-path: /
  port: 9600
  max-http-header-size: 4048576
spring:
  application:
    name: redisson
  redis:
    redisson:
      config: |
        singleServerConfig:
            idleConnectionTimeout: 10000
            connectTimeout: 10000
            timeout: 3000
            retryAttempts: 3
            retryInterval: 1500
            password: East.Com#026
            subscriptionsPerConnection: 5
            address: "redis://10.20.1.79:6379"
            subscriptionConnectionMinimumIdleSize: 1
            subscriptionConnectionPoolSize: 50
            connectionMinimumIdleSize: 32
            connectionPoolSize: 64
            database: 3
            dnsMonitoringInterval: 5000
        threads: 0
        nettyThreads: 0
        codec: !<org.redisson.codec.JsonJacksonCodec> {}
        transportMode: "NIO"
